#!/usr/bin/env python3
"""Status — a section page, built from three files the project maintains.

The other two examples are *kind* pages: one declaration, one output per
data file. This one is the other half of the contract — the project
designs the page itself, section by section, and each section says what it
is built from. The three sections here exist to show the three answers a
section can give:

    overview   INPUTS   — renders a document's content
    work       INPUTS   — renders a data file's content
    notes      LISTING  — renders a directory's shape, never its contents
                VOLATILE — and the output depends on today's date

That is the whole cache contract, which is what makes the render
incremental: edit ``docs/status.md`` and only ``overview`` is rebuilt.
"""

TITLE = "Meridian — release status"
DESCRIPTION = ("Where the Meridian date parser stands on the way to 1.0 — "
               "the status note, the open work, and the release notes on disk.")

# Sections in display order: (id, number, kicker, title, subline, nav label).
# Each id needs a sibling module beside this file.
SECTIONS = [
    ("overview", "01", "Status", "Where 1.0 stands",
     "The numbers and the narrative, both out of docs/status.md", "Status"),
    ("work", "02", "Backlog", "What is left",
     "Every open item before the 1.0 tag, filterable by area", "Work"),
    ("notes", "03", "Record", "Release notes on disk",
     "What has shipped so far — the files, not their contents", "Notes"),
]

HERO_HTML = (
    "<header class='hero'>"
    "<div class='eyebrow'>Meridian · maintainer view</div>"
    "<h1>Release status</h1>"
    "<p>One page the release manager opens: what the status note says, "
    "what is still open, and what has already shipped.</p>"
    "<div class='row'>"
    "<span class='chip'><span class='dot'></span>0.9.0 in flight</span>"
    "<span class='chip'>1.0.0 target 2026-09-30</span>"
    "<span class='chip'>no dependencies</span>"
    "</div></header>"
)

FOOTER_HTML = ("<footer>Generated by the render plugin · {generated} · "
               "self-contained, no external resources · example project, "
               "entirely fictional</footer>")
